//! Pressure-advance calibration tower. Each band holds one K value and prints
//! a slow frame plus a slow-fast-slow line so the transition exercises PA.

use serde::{Deserialize, Serialize};

use crate::strategy::PrinterProfile;

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum PaFirmware {
    Klipper,
    Marlin,
}

impl PaFirmware {
    pub fn parse(name: &str) -> Result<Self, String> {
        match name.trim().to_ascii_lowercase().as_str() {
            "klipper" | "pa" => Ok(PaFirmware::Klipper),
            "marlin" | "la" | "linear" => Ok(PaFirmware::Marlin),
            other => Err(format!("unknown firmware '{other}' (use klipper or marlin)")),
        }
    }

    pub fn as_str(self) -> &'static str {
        match self {
            PaFirmware::Klipper => "klipper",
            PaFirmware::Marlin => "marlin",
        }
    }
}

#[derive(Clone, Debug)]
pub struct PaCalib {
    pub firmware: PaFirmware,
    pub start: f64,
    pub end: f64,
    pub step: f64,
    pub layer_height: f64,
    pub line_width: f64,
    pub band_height: f64,
    pub slow_mm_s: f64,
    pub fast_mm_s: f64,
    pub accel: f64,
    pub profile: PrinterProfile,
}

impl Default for PaCalib {
    fn default() -> Self {
        Self {
            firmware: PaFirmware::Klipper,
            start: 0.0,
            end: 0.08,
            step: 0.01,
            layer_height: 0.2,
            line_width: 0.45,
            band_height: 2.0,
            slow_mm_s: 40.0,
            fast_mm_s: 200.0,
            accel: 3000.0,
            profile: PrinterProfile::default(),
        }
    }
}

#[derive(Clone, Debug, PartialEq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct PaBand {
    pub index: usize,
    pub k: f64,
    pub z0: f64,
    pub z1: f64,
}

#[derive(Clone, Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct PaCalibOutput {
    pub gcode: String,
    pub bands: Vec<PaBand>,
    pub final_e: f64,
    pub slow_mm_s: f64,
    pub fast_mm_s: f64,
}

#[derive(Clone, Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PaCalibRequest {
    pub firmware: String,
    pub start: f64,
    pub end: f64,
    pub step: f64,
    #[serde(default = "default_layer")]
    pub layer_height: f64,
    #[serde(default = "default_band")]
    pub band_height: f64,
    #[serde(default = "default_slow")]
    pub slow_mm_s: f64,
    #[serde(default = "default_fast")]
    pub fast_mm_s: f64,
    #[serde(default = "default_accel")]
    pub accel: f64,
    #[serde(default)]
    pub printer: Option<PrinterProfile>,
}

fn default_layer() -> f64 {
    0.2
}
fn default_band() -> f64 {
    2.0
}
fn default_slow() -> f64 {
    40.0
}
fn default_fast() -> f64 {
    200.0
}
fn default_accel() -> f64 {
    3000.0
}

pub fn pressure_advance_from_request(req: &PaCalibRequest) -> Result<PaCalibOutput, String> {
    pressure_advance_tower(&PaCalib {
        firmware: PaFirmware::parse(&req.firmware)?,
        start: req.start,
        end: req.end,
        step: req.step,
        layer_height: req.layer_height,
        band_height: req.band_height,
        slow_mm_s: req.slow_mm_s,
        fast_mm_s: req.fast_mm_s,
        accel: req.accel,
        profile: req.printer.clone().unwrap_or_default(),
        line_width: 0.45,
    })
}

pub fn pressure_advance_tower(opts: &PaCalib) -> Result<PaCalibOutput, String> {
    if opts.step <= 1e-6 {
        return Err("PA step must be positive".into());
    }
    if opts.end + 1e-9 < opts.start {
        return Err("PA end is below the start".into());
    }
    let layer_h = opts.layer_height.clamp(0.08, 0.4);
    let width = opts.line_width.clamp(0.2, 1.0);
    let band_h = opts.band_height.max(layer_h);
    let layers_per = (band_h / layer_h).round().max(1.0) as usize;
    let mut ks = Vec::new();
    let mut k = opts.start;
    while ks.len() < 80 && k <= opts.end + opts.step * 0.25 {
        ks.push((k * 1.0e6).round() / 1.0e6);
        k += opts.step;
    }
    if ks.is_empty() {
        return Err("PA range produced no bands".into());
    }
    let area = (width * layer_h).max(1e-6);
    let cap = if opts.profile.max_volumetric_mm3_s.is_finite() && opts.profile.max_volumetric_mm3_s > 0.0
    {
        opts.profile.max_volumetric_mm3_s / area
    } else {
        500.0
    };
    let slow = opts.slow_mm_s.clamp(10.0, cap);
    let fast = opts.fast_mm_s.max(slow + 5.0).min(cap.max(slow + 5.0));
    let accel = opts.accel.clamp(100.0, 20000.0);
    let fil = std::f64::consts::PI * (opts.profile.filament_diameter * 0.5).powi(2);

    let mut bands = Vec::new();
    let mut out = String::new();
    out.push_str("; generated by Lime Slice — pressure advance calibration\n");
    out.push_str(&format!("; PA_CALIBRATION firmware={}\n", opts.firmware.as_str()));
    out.push_str(&format!(
        "; slow {:.1} mm/s  fast {:.1} mm/s  accel {:.0}  layer {:.3}  width {:.3}\n",
        slow, fast, accel, layer_h, width
    ));
    out.push_str("; PA_LEGEND\n");
    for (i, k) in ks.iter().enumerate() {
        let z0 = (i * layers_per) as f64 * layer_h + layer_h;
        let z1 = ((i + 1) * layers_per) as f64 * layer_h;
        bands.push(PaBand {
            index: i,
            k: *k,
            z0,
            z1,
        });
        out.push_str(&format!(
            "; PA_BAND index={i} k={k:.4} z0={z0:.3} z1={z1:.3}\n"
        ));
    }
    let p = &opts.profile;
    out.push_str(&format!("M140 S{:.0}\nM104 S{:.0}\n", p.bed_temp, p.nozzle_temp));
    out.push_str(&format!("M190 S{:.0}\nM109 S{:.0}\n", p.bed_temp, p.nozzle_temp));
    out.push_str("G21\nG90\nM82\nG28\nG92 E0\n");
    out.push_str(&format!("M204 S{accel:.0}\n"));

    let mut pen = Pen {
        out: &mut out,
        e: 0.0,
        x: 0.0,
        y: 0.0,
        known: false,
        width,
        height: layer_h,
        fil,
    };
    let x0 = 20.0;
    let y0 = 20.0;
    let length = 50.0;
    for band in &bands {
        pen.out.push_str(&format!(
            "; PA_BAND_START index={} k={:.4} z0={:.3} z1={:.3}\n",
            band.index, band.k, band.z0, band.z1
        ));
        match opts.firmware {
            PaFirmware::Klipper => {
                pen.out
                    .push_str(&format!("SET_PRESSURE_ADVANCE ADVANCE={:.4}\n", band.k));
            }
            PaFirmware::Marlin => {
                pen.out.push_str(&format!("M900 K{:.4}\n", band.k));
            }
        }
        let first_layer = ((band.z0 / layer_h).round() as usize).saturating_sub(1);
        let last_layer = (band.z1 / layer_h).round() as usize;
        for layer_i in first_layer..last_layer {
            let z = (layer_i as f64 + 1.0) * layer_h;
            pen.out.push_str(&format!(
                ";LAYER:{layer_i} Z:{z:.3} H:{layer_h:.3} pa k={:.4}\n",
                band.k
            ));
            pen.out.push_str(&format!("G1 Z{z:.3} F7200\n"));
            pen.comment("TYPE:PA_SLOW");
            pen.travel(x0, y0, slow);
            pen.extrude(x0 + length, y0, slow);
            pen.extrude(x0 + length, y0 + 6.0, slow);
            pen.extrude(x0, y0 + 6.0, slow);
            pen.extrude(x0, y0, slow);
            let y = y0 + 3.0;
            pen.comment("TYPE:PA_SLOW");
            pen.travel(x0, y, slow);
            pen.extrude(x0 + 8.0, y, slow);
            pen.comment("TYPE:PA_FAST");
            pen.extrude(x0 + 38.0, y, fast);
            pen.comment("TYPE:PA_SLOW");
            pen.extrude(x0 + 46.0, y, slow);
        }
    }
    let e = pen.e;
    let z_park = bands.last().unwrap().z1 + 10.0;
    drop(pen);
    let parked = e - 1.0;
    out.push_str(&format!("G1 E{parked:.5} F1800\n"));
    out.push_str(&format!("G1 Z{z_park:.3} F600\n"));
    out.push_str(&format!("; FILAMENT_E:{e:.3}\n"));
    out.push_str("M104 S0\nM140 S0\nM84\n");
    Ok(PaCalibOutput {
        gcode: out,
        bands,
        final_e: e,
        slow_mm_s: slow,
        fast_mm_s: fast,
    })
}

struct Pen<'a> {
    out: &'a mut String,
    e: f64,
    x: f64,
    y: f64,
    known: bool,
    width: f64,
    height: f64,
    fil: f64,
}

impl Pen<'_> {
    fn comment(&mut self, text: &str) {
        self.out.push_str("; ");
        self.out.push_str(text);
        self.out.push('\n');
    }

    fn travel(&mut self, x: f64, y: f64, speed: f64) {
        let f = (speed * 60.0).round() as i32;
        self.out.push_str(&format!("G1 X{x:.3} Y{y:.3} F{f}\n"));
        self.x = x;
        self.y = y;
        self.known = true;
    }

    fn extrude(&mut self, x: f64, y: f64, speed: f64) {
        let len = if self.known {
            (x - self.x).hypot(y - self.y)
        } else {
            0.0
        };
        if len < 1e-6 {
            self.travel(x, y, speed);
            return;
        }
        self.e += len * self.width * self.height / self.fil;
        let f = (speed * 60.0).round() as i32;
        self.out
            .push_str(&format!("G1 X{x:.3} Y{y:.3} E{:.5} F{f}\n", self.e));
        self.x = x;
        self.y = y;
        self.known = true;
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn ks(gcode: &str) -> Vec<f64> {
        gcode
            .lines()
            .filter_map(|l| l.strip_prefix("SET_PRESSURE_ADVANCE ADVANCE="))
            .filter_map(|v| v.parse().ok())
            .collect()
    }

    #[test]
    fn klipper_bands_step_and_sit_at_the_right_z() {
        let out = pressure_advance_tower(&PaCalib {
            end: 0.04,
            step: 0.02,
            band_height: 1.0,
            ..PaCalib::default()
        })
        .unwrap();
        let values = ks(&out.gcode);
        assert_eq!(values, vec![0.0, 0.02, 0.04]);
        assert_eq!(out.bands.len(), 3);
        assert!((out.bands[0].z0 - 0.2).abs() < 1e-6);
        assert!((out.bands[0].z1 - 1.0).abs() < 1e-6);
        assert!((out.bands[1].z0 - 1.2).abs() < 1e-6);
        assert!((out.bands[2].z1 - 3.0).abs() < 1e-6);
        assert!(out.final_e > 10.0 && out.final_e < 500.0, "E {}", out.final_e);
        assert!(out.gcode.contains("TYPE:PA_FAST"));
        assert!(out.gcode.contains("F2400"), "slow 40 mm/s");
        assert!(out.fast_mm_s > out.slow_mm_s + 20.0);
        let fast_f = format!("F{}", (out.fast_mm_s * 60.0).round() as i32);
        assert!(out.gcode.contains(&fast_f));
        // Every band's layers fall inside its Z window.
        let mut band_i = 0usize;
        for line in out.gcode.lines() {
            if let Some(rest) = line.strip_prefix(";LAYER:") {
                let mut z = 0.0;
                for tok in rest.split_whitespace() {
                    if let Some(v) = tok.strip_prefix("Z:") {
                        z = v.parse().unwrap();
                    }
                }
                let band = &out.bands[band_i.min(out.bands.len() - 1)];
                if z > band.z1 + 1e-6 {
                    band_i += 1;
                }
                let band = &out.bands[band_i];
                assert!(
                    z + 1e-6 >= band.z0 && z <= band.z1 + 1e-6,
                    "layer Z {z} outside band {} {:.3}..{:.3}",
                    band.index,
                    band.z0,
                    band.z1
                );
            }
        }
    }

    #[test]
    fn marlin_emits_m900_and_rejects_a_bad_range() {
        let out = pressure_advance_tower(&PaCalib {
            firmware: PaFirmware::Marlin,
            start: 0.1,
            end: 0.3,
            step: 0.1,
            band_height: 0.4,
            ..PaCalib::default()
        })
        .unwrap();
        assert!(out.gcode.contains("M900 K0.1000"));
        assert!(out.gcode.contains("M900 K0.2000"));
        assert!(out.gcode.contains("M900 K0.3000"));
        assert!(!out.gcode.contains("SET_PRESSURE_ADVANCE"));
        assert!(pressure_advance_tower(&PaCalib {
            end: 0.0,
            start: 0.1,
            ..PaCalib::default()
        })
        .is_err());
    }
}
