//! Pressure-advance calibration tower. Each band holds one K value and prints
//! a slow frame plus a slow-fast-slow line so the transition exercises PA.

use serde::{Deserialize, Serialize};

use crate::strategy::PrinterProfile;

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum PaFirmware {
    Klipper,
    Marlin,
}

impl PaFirmware {
    pub fn parse(name: &str) -> Result<Self, String> {
        match name.trim().to_ascii_lowercase().as_str() {
            "klipper" | "pa" => Ok(PaFirmware::Klipper),
            "marlin" | "la" | "linear" => Ok(PaFirmware::Marlin),
            other => Err(format!("unknown firmware '{other}' (use klipper or marlin)")),
        }
    }

    pub fn as_str(self) -> &'static str {
        match self {
            PaFirmware::Klipper => "klipper",
            PaFirmware::Marlin => "marlin",
        }
    }
}

#[derive(Clone, Debug)]
pub struct PaCalib {
    pub firmware: PaFirmware,
    pub start: f64,
    pub end: f64,
    pub step: f64,
    pub layer_height: f64,
    pub line_width: f64,
    pub band_height: f64,
    pub slow_mm_s: f64,
    pub fast_mm_s: f64,
    pub accel: f64,
    pub profile: PrinterProfile,
}

impl Default for PaCalib {
    fn default() -> Self {
        Self {
            firmware: PaFirmware::Klipper,
            start: 0.0,
            end: 0.08,
            step: 0.01,
            layer_height: 0.2,
            line_width: 0.45,
            band_height: 2.0,
            slow_mm_s: 40.0,
            fast_mm_s: 200.0,
            accel: 3000.0,
            profile: PrinterProfile::default(),
        }
    }
}

#[derive(Clone, Debug, PartialEq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct PaBand {
    pub index: usize,
    pub k: f64,
    pub z0: f64,
    pub z1: f64,
}

#[derive(Clone, Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct PaCalibOutput {
    pub gcode: String,
    pub bands: Vec<PaBand>,
    pub final_e: f64,
    pub slow_mm_s: f64,
    pub fast_mm_s: f64,
}

#[derive(Clone, Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PaCalibRequest {
    pub firmware: String,
    pub start: f64,
    pub end: f64,
    pub step: f64,
    #[serde(default = "default_layer")]
    pub layer_height: f64,
    #[serde(default = "default_band")]
    pub band_height: f64,
    #[serde(default = "default_slow")]
    pub slow_mm_s: f64,
    #[serde(default = "default_fast")]
    pub fast_mm_s: f64,
    #[serde(default = "default_accel")]
    pub accel: f64,
    #[serde(default)]
    pub printer: Option<PrinterProfile>,
}

fn default_layer() -> f64 {
    0.2
}
fn default_band() -> f64 {
    2.0
}
fn default_slow() -> f64 {
    40.0
}
fn default_fast() -> f64 {
    200.0
}
fn default_accel() -> f64 {
    3000.0
}

pub fn pressure_advance_from_request(req: &PaCalibRequest) -> Result<PaCalibOutput, String> {
    pressure_advance_tower(&PaCalib {
        firmware: PaFirmware::parse(&req.firmware)?,
        start: req.start,
        end: req.end,
        step: req.step,
        layer_height: req.layer_height,
        band_height: req.band_height,
        slow_mm_s: req.slow_mm_s,
        fast_mm_s: req.fast_mm_s,
        accel: req.accel,
        profile: req.printer.clone().unwrap_or_default(),
        line_width: 0.45,
    })
}

pub fn pressure_advance_tower(opts: &PaCalib) -> Result<PaCalibOutput, String> {
    if opts.step <= 1e-6 {
        return Err("PA step must be positive".into());
    }
    if opts.end + 1e-9 < opts.start {
        return Err("PA end is below the start".into());
    }
    let layer_h = opts.layer_height.clamp(0.08, 0.4);
    let width = opts.line_width.clamp(0.2, 1.0);
    let band_h = opts.band_height.max(layer_h);
    let layers_per = (band_h / layer_h).round().max(1.0) as usize;
    let mut ks = Vec::new();
    let mut k = opts.start;
    while ks.len() < 80 && k <= opts.end + opts.step * 0.25 {
        ks.push((k * 1.0e6).round() / 1.0e6);
        k += opts.step;
    }
    if ks.is_empty() {
        return Err("PA range produced no bands".into());
    }
    let area = (width * layer_h).max(1e-6);
    let cap = if opts.profile.max_volumetric_mm3_s.is_finite() && opts.profile.max_volumetric_mm3_s > 0.0
    {
        opts.profile.max_volumetric_mm3_s / area
    } else {
        500.0
    };
    // A printer that cannot reach 10 mm/s at this bead prints at its cap.
    let slow = opts.slow_mm_s.clamp(cap.min(10.0), cap);
    let fast = opts.fast_mm_s.max(slow + 5.0).min(cap.max(slow + 5.0));
    let accel = opts.accel.clamp(100.0, 20000.0);
    let fil = std::f64::consts::PI * (opts.profile.filament_diameter * 0.5).powi(2);

    let mut bands = Vec::new();
    let mut out = String::new();
    out.push_str("; generated by Lime Slice — pressure advance calibration\n");
    let firmware = opts.firmware.as_str();
    out.push_str(&format!("; PA_CALIBRATION firmware={firmware}\n"));
    out.push_str(&format!(
        "; slow {slow:.1} mm/s  fast {fast:.1} mm/s  accel {accel:.0}  layer {layer_h:.3}  width {width:.3}\n"
    ));
    out.push_str("; PA_LEGEND\n");
    for (i, k) in ks.iter().enumerate() {
        let z0 = (i * layers_per) as f64 * layer_h + layer_h;
        let z1 = ((i + 1) * layers_per) as f64 * layer_h;
        bands.push(PaBand {
            index: i,
            k: *k,
            z0,
            z1,
        });
        out.push_str(&format!(
            "; PA_BAND index={i} k={k:.4} z0={z0:.3} z1={z1:.3}\n"
        ));
    }
    let p = &opts.profile;
    out.push_str(&format!("M140 S{:.0}\nM104 S{:.0}\n", p.bed_temp, p.nozzle_temp));
    out.push_str(&format!("M190 S{:.0}\nM109 S{:.0}\n", p.bed_temp, p.nozzle_temp));
    out.push_str("G21\nG90\nM82\nG28\nG92 E0\n");
    out.push_str(&format!("M204 S{accel:.0}\n"));

    let x0 = 20.0;
    let y0 = 20.0;
    let length = 50.0;
    let e = {
        let mut pen = Pen {
            out: &mut out,
            e: 0.0,
            x: 0.0,
            y: 0.0,
            known: false,
            width,
            height: layer_h,
            fil,
            flow: 1.0,
        };
        for band in &bands {
        pen.out.push_str(&format!(
            "; PA_BAND_START index={} k={:.4} z0={:.3} z1={:.3}\n",
            band.index, band.k, band.z0, band.z1
        ));
        match opts.firmware {
            PaFirmware::Klipper => {
                pen.out
                    .push_str(&format!("SET_PRESSURE_ADVANCE ADVANCE={:.4}\n", band.k));
            }
            PaFirmware::Marlin => {
                pen.out.push_str(&format!("M900 K{:.4}\n", band.k));
            }
        }
        let first_layer = ((band.z0 / layer_h).round() as usize).saturating_sub(1);
        let last_layer = (band.z1 / layer_h).round() as usize;
        for layer_i in first_layer..last_layer {
            let z = (layer_i as f64 + 1.0) * layer_h;
            pen.out.push_str(&format!(
                ";LAYER:{layer_i} Z:{z:.3} H:{layer_h:.3} pa k={:.4}\n",
                band.k
            ));
            pen.out.push_str(&format!("G1 Z{z:.3} F7200\n"));
            pen.layer_fan(layer_i);
            pen.comment("TYPE:PA_SLOW");
            pen.travel(x0, y0, slow);
            pen.extrude(x0 + length, y0, slow);
            pen.extrude(x0 + length, y0 + 6.0, slow);
            pen.extrude(x0, y0 + 6.0, slow);
            pen.extrude(x0, y0, slow);
            let y = y0 + 3.0;
            pen.comment("TYPE:PA_SLOW");
            pen.travel(x0, y, slow);
            pen.extrude(x0 + 8.0, y, slow);
            pen.comment("TYPE:PA_FAST");
            pen.extrude(x0 + 38.0, y, fast);
            pen.comment("TYPE:PA_SLOW");
            pen.extrude(x0 + 46.0, y, slow);
        }
        }
        pen.e
    };
    let z_park = bands.last().unwrap().z1 + 10.0;
    let parked = e - 1.0;
    out.push_str(&format!("G1 E{parked:.5} F1800\n"));
    out.push_str(&format!("G1 Z{z_park:.3} F600\n"));
    out.push_str(&format!("; FILAMENT_E:{e:.3}\n"));
    out.push_str("M106 S0\nM104 S0\nM140 S0\nM84\n");
    Ok(PaCalibOutput {
        gcode: out,
        bands,
        final_e: e,
        slow_mm_s: slow,
        fast_mm_s: fast,
    })
}

/// Flow-multiplier tower. Each band is one hollow single wall at one
/// multiplier. Extrusion length is scaled by that multiplier. `M221` is not
/// sent, so a firmware flow override cannot stack on top.
#[derive(Clone, Debug)]
pub struct FlowCalib {
    pub start: f64,
    pub end: f64,
    pub step: f64,
    pub layer_height: f64,
    pub line_width: f64,
    pub band_height: f64,
    pub speed_mm_s: f64,
    pub profile: PrinterProfile,
}

impl Default for FlowCalib {
    fn default() -> Self {
        Self {
            start: 0.9,
            end: 1.1,
            step: 0.05,
            layer_height: 0.2,
            line_width: 0.45,
            band_height: 5.0,
            speed_mm_s: 40.0,
            profile: PrinterProfile::default(),
        }
    }
}

#[derive(Clone, Debug, PartialEq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct FlowBand {
    pub index: usize,
    pub flow: f64,
    pub z0: f64,
    pub z1: f64,
}

#[derive(Clone, Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct FlowCalibOutput {
    pub gcode: String,
    pub bands: Vec<FlowBand>,
    pub final_e: f64,
    pub speed_mm_s: f64,
}

#[derive(Clone, Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FlowCalibRequest {
    pub start: f64,
    pub end: f64,
    pub step: f64,
    #[serde(default = "default_layer")]
    pub layer_height: f64,
    #[serde(default = "default_flow_band")]
    pub band_height: f64,
    #[serde(default = "default_flow_speed")]
    pub speed_mm_s: f64,
    #[serde(default)]
    pub printer: Option<PrinterProfile>,
}

fn default_flow_band() -> f64 {
    5.0
}
fn default_flow_speed() -> f64 {
    40.0
}

pub fn flow_from_request(req: &FlowCalibRequest) -> Result<FlowCalibOutput, String> {
    flow_tower(&FlowCalib {
        start: req.start,
        end: req.end,
        step: req.step,
        layer_height: req.layer_height,
        band_height: req.band_height,
        speed_mm_s: req.speed_mm_s,
        profile: req.printer.clone().unwrap_or_default(),
        line_width: 0.45,
    })
}

pub fn flow_tower(opts: &FlowCalib) -> Result<FlowCalibOutput, String> {
    if !opts.start.is_finite() || !opts.end.is_finite() || !opts.step.is_finite() {
        return Err("flow start, end, and step must be finite".into());
    }
    if opts.step <= 1e-6 {
        return Err("flow step must be positive".into());
    }
    if opts.end + 1e-9 < opts.start {
        return Err("flow end is below the start".into());
    }
    let mut flows = Vec::new();
    let mut k = opts.start;
    while flows.len() < 40 && k <= opts.end + opts.step * 0.25 {
        let value = (k * 1000.0).round() / 1000.0;
        if !(0.5..=1.5).contains(&value) {
            return Err(format!("flow {value} must be from 0.5 to 1.5"));
        }
        flows.push(value);
        k += opts.step;
    }
    if flows.is_empty() {
        return Err("flow range produced no bands".into());
    }
    let layer_h = opts.layer_height.clamp(0.08, 0.4);
    let width = opts.line_width.clamp(0.2, 1.0);
    let band_h = opts.band_height.max(layer_h);
    let layers_per = (band_h / layer_h).round().max(1.0) as usize;
    let area = (width * layer_h).max(1e-6);
    let cap = if opts.profile.max_volumetric_mm3_s.is_finite()
        && opts.profile.max_volumetric_mm3_s > 0.0
    {
        opts.profile.max_volumetric_mm3_s / area
    } else {
        500.0
    };
    let speed = opts.speed_mm_s.clamp(cap.min(10.0), cap);
    let fil = std::f64::consts::PI * (opts.profile.filament_diameter * 0.5).powi(2);

    let mut bands = Vec::new();
    let mut out = String::new();
    out.push_str("; generated by Lime Slice — flow calibration\n");
    out.push_str("; FLOW_CALIBRATION\n");
    out.push_str(&format!(
        "; speed {speed:.1} mm/s  layer {layer_h:.3}  width {width:.3}\n"
    ));
    out.push_str("; FLOW_LEGEND\n");
    for (i, flow) in flows.iter().enumerate() {
        let z0 = (i * layers_per) as f64 * layer_h + layer_h;
        let z1 = ((i + 1) * layers_per) as f64 * layer_h;
        bands.push(FlowBand {
            index: i,
            flow: *flow,
            z0,
            z1,
        });
        out.push_str(&format!(
            "; FLOW_BAND index={i} flow={flow:.3} z0={z0:.3} z1={z1:.3}\n"
        ));
    }
    let p = &opts.profile;
    out.push_str(&format!("M140 S{:.0}\nM104 S{:.0}\n", p.bed_temp, p.nozzle_temp));
    out.push_str(&format!("M190 S{:.0}\nM109 S{:.0}\n", p.bed_temp, p.nozzle_temp));
    out.push_str("G21\nG90\nM82\nG28\nG92 E0\n");

    let x0 = 20.0;
    let y0 = 20.0;
    let side = 30.0;
    let e = {
        let mut pen = Pen {
            out: &mut out,
            e: 0.0,
            x: 0.0,
            y: 0.0,
            known: false,
            width,
            height: layer_h,
            fil,
            flow: 1.0,
        };
        for band in &bands {
            pen.flow = band.flow;
            pen.out.push_str(&format!(
                "; FLOW_BAND_START index={} flow={:.3} z0={:.3} z1={:.3}\n",
                band.index, band.flow, band.z0, band.z1
            ));
            let first_layer = ((band.z0 / layer_h).round() as usize).saturating_sub(1);
            let last_layer = (band.z1 / layer_h).round() as usize;
            for layer_i in first_layer..last_layer {
                let z = (layer_i as f64 + 1.0) * layer_h;
                pen.out.push_str(&format!(
                    ";LAYER:{layer_i} Z:{z:.3} H:{layer_h:.3} flow={:.3}\n",
                    band.flow
                ));
                pen.out.push_str(&format!("G1 Z{z:.3} F7200\n"));
                pen.layer_fan(layer_i);
                pen.comment("TYPE:FLOW_WALL");
                pen.travel(x0, y0, speed);
                pen.extrude(x0 + side, y0, speed);
                pen.extrude(x0 + side, y0 + side, speed);
                pen.extrude(x0, y0 + side, speed);
                pen.extrude(x0, y0, speed);
            }
        }
        pen.e
    };
    let z_park = bands.last().unwrap().z1 + 10.0;
    let parked = e - 1.0;
    out.push_str(&format!("G1 E{parked:.5} F1800\n"));
    out.push_str(&format!("G1 Z{z_park:.3} F600\n"));
    out.push_str(&format!("; FILAMENT_E:{e:.3}\n"));
    out.push_str("M106 S0\nM104 S0\nM140 S0\nM84\n");
    Ok(FlowCalibOutput {
        gcode: out,
        bands,
        final_e: e,
        speed_mm_s: speed,
    })
}

/// Nozzle-temperature tower. Each band is one hollow single wall, and the
/// nozzle waits at that band's temperature before the wall starts.
#[derive(Clone, Debug)]
pub struct TempCalib {
    pub start: f64,
    pub end: f64,
    pub step: f64,
    pub layer_height: f64,
    pub line_width: f64,
    pub band_height: f64,
    pub speed_mm_s: f64,
    pub profile: PrinterProfile,
}

impl Default for TempCalib {
    fn default() -> Self {
        Self {
            start: 190.0,
            end: 230.0,
            step: 5.0,
            layer_height: 0.2,
            line_width: 0.45,
            band_height: 5.0,
            speed_mm_s: 40.0,
            profile: PrinterProfile::default(),
        }
    }
}

#[derive(Clone, Debug, PartialEq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct TempBand {
    pub index: usize,
    pub temp: f64,
    pub z0: f64,
    pub z1: f64,
}

#[derive(Clone, Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct TempCalibOutput {
    pub gcode: String,
    pub bands: Vec<TempBand>,
    pub final_e: f64,
    pub speed_mm_s: f64,
}

#[derive(Clone, Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TempCalibRequest {
    pub start: f64,
    pub end: f64,
    pub step: f64,
    #[serde(default = "default_layer")]
    pub layer_height: f64,
    #[serde(default = "default_temp_band")]
    pub band_height: f64,
    #[serde(default = "default_temp_speed")]
    pub speed_mm_s: f64,
    #[serde(default)]
    pub printer: Option<PrinterProfile>,
}

fn default_temp_band() -> f64 {
    5.0
}

fn default_temp_speed() -> f64 {
    40.0
}

pub fn temperature_from_request(req: &TempCalibRequest) -> Result<TempCalibOutput, String> {
    temperature_tower(&TempCalib {
        start: req.start,
        end: req.end,
        step: req.step,
        layer_height: req.layer_height,
        band_height: req.band_height,
        speed_mm_s: req.speed_mm_s,
        profile: req.printer.clone().unwrap_or_default(),
        line_width: 0.45,
    })
}

/// How far above the tower top the nozzle waits for a new band temperature.
const TEMP_WAIT_LIFT_MM: f64 = 5.0;

pub fn temperature_tower(opts: &TempCalib) -> Result<TempCalibOutput, String> {
    if !opts.start.is_finite() || !opts.end.is_finite() || !opts.step.is_finite() {
        return Err("temperature start, end, and step must be finite".into());
    }
    if opts.step < 1.0 - 1e-9 {
        return Err("temperature step must be at least 1 °C".into());
    }
    if opts.end + 1e-9 < opts.start {
        return Err("temperature end is below the start".into());
    }
    let mut temps = Vec::new();
    let mut t = opts.start;
    while temps.len() < 40 && t <= opts.end + opts.step * 0.25 {
        let temp = t.round();
        if !(150.0..=320.0).contains(&temp) {
            return Err(format!("temperature {temp} °C must be from 150 to 320"));
        }
        temps.push(temp);
        t += opts.step;
    }
    if temps.is_empty() {
        return Err("temperature range produced no bands".into());
    }
    let layer_h = opts.layer_height.clamp(0.08, 0.4);
    let width = opts.line_width.clamp(0.2, 1.0);
    let band_h = opts.band_height.max(layer_h);
    let layers_per = (band_h / layer_h).round().max(1.0) as usize;
    let area = (width * layer_h).max(1e-6);
    let cap = if opts.profile.max_volumetric_mm3_s.is_finite()
        && opts.profile.max_volumetric_mm3_s > 0.0
    {
        opts.profile.max_volumetric_mm3_s / area
    } else {
        500.0
    };
    let speed = opts.speed_mm_s.clamp(cap.min(10.0), cap);
    let fil = std::f64::consts::PI * (opts.profile.filament_diameter * 0.5).powi(2);

    let mut bands = Vec::new();
    let mut out = String::new();
    out.push_str("; generated by Lime Slice — temperature calibration\n");
    out.push_str("; TEMP_CALIBRATION\n");
    out.push_str(&format!(
        "; speed {speed:.1} mm/s  layer {layer_h:.3}  width {width:.3}\n"
    ));
    out.push_str("; TEMP_LEGEND\n");
    for (i, temp) in temps.iter().enumerate() {
        let z0 = (i * layers_per) as f64 * layer_h + layer_h;
        let z1 = ((i + 1) * layers_per) as f64 * layer_h;
        bands.push(TempBand {
            index: i,
            temp: *temp,
            z0,
            z1,
        });
        out.push_str(&format!(
            "; TEMP_BAND index={i} temp={temp:.0} z0={z0:.3} z1={z1:.3}\n"
        ));
    }
    let p = &opts.profile;
    out.push_str(&format!("M140 S{:.0}\nM104 S{:.0}\n", p.bed_temp, temps[0]));
    out.push_str(&format!("M190 S{:.0}\nM109 S{:.0}\n", p.bed_temp, temps[0]));
    out.push_str("G21\nG90\nM82\nG28\nG92 E0\n");

    let x0 = 20.0;
    let y0 = 20.0;
    let side = 30.0;
    let e = {
        let mut pen = Pen {
            out: &mut out,
            e: 0.0,
            x: 0.0,
            y: 0.0,
            known: false,
            width,
            height: layer_h,
            fil,
            flow: 1.0,
        };
        for band in &bands {
            pen.out.push_str(&format!(
                "; TEMP_BAND_START index={} temp={:.0} z0={:.3} z1={:.3}\n",
                band.index, band.temp, band.z0, band.z1
            ));
            // Wait clear of the tower, so the hot nozzle does not sit on
            // the top layer and ooze onto it while the temperature changes.
            if band.index > 0 {
                pen.filament(-1.0, 30.0);
                pen.out
                    .push_str(&format!("G1 Z{:.3} F600\n", band.z0 + TEMP_WAIT_LIFT_MM));
                pen.travel(x0 - 10.0, y0 - 10.0, speed);
            }
            pen.out
                .push_str(&format!("M104 S{:.0}\nM109 S{:.0}\n", band.temp, band.temp));
            if band.index > 0 {
                pen.filament(1.0, 30.0);
            }
            let first_layer = ((band.z0 / layer_h).round() as usize).saturating_sub(1);
            let last_layer = (band.z1 / layer_h).round() as usize;
            for layer_i in first_layer..last_layer {
                let z = (layer_i as f64 + 1.0) * layer_h;
                pen.out.push_str(&format!(
                    ";LAYER:{layer_i} Z:{z:.3} H:{layer_h:.3} temp={:.0}\n",
                    band.temp
                ));
                pen.out.push_str(&format!("G1 Z{z:.3} F7200\n"));
                pen.layer_fan(layer_i);
                pen.comment("TYPE:TEMP_WALL");
                pen.travel(x0, y0, speed);
                pen.extrude(x0 + side, y0, speed);
                pen.extrude(x0 + side, y0 + side, speed);
                pen.extrude(x0, y0 + side, speed);
                pen.extrude(x0, y0, speed);
            }
        }
        pen.e
    };
    let z_park = bands.last().unwrap().z1 + 10.0;
    let parked = e - 1.0;
    out.push_str(&format!("G1 E{parked:.5} F1800\n"));
    out.push_str(&format!("G1 Z{z_park:.3} F600\n"));
    out.push_str(&format!("; FILAMENT_E:{e:.3}\n"));
    out.push_str("M106 S0\nM104 S0\nM140 S0\nM84\n");
    Ok(TempCalibOutput {
        gcode: out,
        bands,
        final_e: e,
        speed_mm_s: speed,
    })
}

/// Two posts per layer. The travel between them retracts by that band's length.
#[derive(Clone, Debug)]
pub struct RetractCalib {
    pub start: f64,
    pub end: f64,
    pub step: f64,
    pub layer_height: f64,
    pub line_width: f64,
    pub band_height: f64,
    pub speed_mm_s: f64,
    pub profile: PrinterProfile,
}

impl Default for RetractCalib {
    fn default() -> Self {
        Self {
            start: 0.2,
            end: 1.2,
            step: 0.2,
            layer_height: 0.2,
            line_width: 0.45,
            band_height: 5.0,
            speed_mm_s: 30.0,
            profile: PrinterProfile::default(),
        }
    }
}

#[derive(Clone, Debug, PartialEq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct RetractBand {
    pub index: usize,
    pub length: f64,
    pub z0: f64,
    pub z1: f64,
}

#[derive(Clone, Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct RetractCalibOutput {
    pub gcode: String,
    pub bands: Vec<RetractBand>,
    pub final_e: f64,
    pub speed_mm_s: f64,
}

#[derive(Clone, Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RetractCalibRequest {
    pub start: f64,
    pub end: f64,
    pub step: f64,
    #[serde(default = "default_layer")]
    pub layer_height: f64,
    #[serde(default = "default_retract_band")]
    pub band_height: f64,
    #[serde(default = "default_retract_speed")]
    pub speed_mm_s: f64,
    #[serde(default)]
    pub printer: Option<PrinterProfile>,
}

fn default_retract_band() -> f64 {
    5.0
}

fn default_retract_speed() -> f64 {
    30.0
}

pub fn retract_from_request(req: &RetractCalibRequest) -> Result<RetractCalibOutput, String> {
    retract_tower(&RetractCalib {
        start: req.start,
        end: req.end,
        step: req.step,
        layer_height: req.layer_height,
        band_height: req.band_height,
        speed_mm_s: req.speed_mm_s,
        profile: req.printer.clone().unwrap_or_default(),
        line_width: 0.45,
    })
}

pub fn retract_tower(opts: &RetractCalib) -> Result<RetractCalibOutput, String> {
    if !opts.start.is_finite() || !opts.end.is_finite() || !opts.step.is_finite() {
        return Err("retract start, end, and step must be finite".into());
    }
    if opts.step < 0.05 - 1e-9 {
        return Err("retract step must be at least 0.05 mm".into());
    }
    if opts.end + 1e-9 < opts.start {
        return Err("retract end is below the start".into());
    }
    if !opts.speed_mm_s.is_finite() || !(5.0..=80.0).contains(&opts.speed_mm_s) {
        return Err(format!(
            "retract speed {} mm/s must be from 5 to 80",
            opts.speed_mm_s
        ));
    }
    let mut lengths = Vec::new();
    let mut k = opts.start;
    while lengths.len() < 40 && k <= opts.end + opts.step * 0.25 {
        let length = (k * 1000.0).round() / 1000.0;
        if !(0.0..=5.0).contains(&length) {
            return Err(format!("retract length {length} mm must be from 0 to 5"));
        }
        lengths.push(length);
        k += opts.step;
    }
    if lengths.is_empty() {
        return Err("retract range produced no bands".into());
    }
    let layer_h = opts.layer_height.clamp(0.08, 0.4);
    let width = opts.line_width.clamp(0.2, 1.0);
    let band_h = opts.band_height.max(layer_h);
    let layers_per = (band_h / layer_h).round().max(1.0) as usize;
    let speed = 40.0_f64;
    let retract_speed = opts.speed_mm_s;
    let fil = std::f64::consts::PI * (opts.profile.filament_diameter * 0.5).powi(2);

    let mut bands = Vec::new();
    let mut out = String::new();
    out.push_str("; generated by Lime Slice — retraction calibration\n");
    out.push_str("; RETRACT_CALIBRATION\n");
    out.push_str(&format!(
        "; retract speed {retract_speed:.0} mm/s  layer {layer_h:.3}  width {width:.3}\n"
    ));
    out.push_str("; RETRACT_LEGEND\n");
    for (i, length) in lengths.iter().enumerate() {
        let z0 = (i * layers_per) as f64 * layer_h + layer_h;
        let z1 = ((i + 1) * layers_per) as f64 * layer_h;
        bands.push(RetractBand {
            index: i,
            length: *length,
            z0,
            z1,
        });
        out.push_str(&format!(
            "; RETRACT_BAND index={i} length={length:.3} z0={z0:.3} z1={z1:.3}\n"
        ));
    }
    let p = &opts.profile;
    out.push_str(&format!("M140 S{:.0}\nM104 S{:.0}\n", p.bed_temp, p.nozzle_temp));
    out.push_str(&format!("M190 S{:.0}\nM109 S{:.0}\n", p.bed_temp, p.nozzle_temp));
    out.push_str("G21\nG90\nM82\nG28\nG92 E0\n");

    let ax = 20.0;
    let ay = 20.0;
    let bx = 50.0;
    let by = 20.0;
    let side = 8.0;
    let e = {
        let mut pen = Pen {
            out: &mut out,
            e: 0.0,
            x: 0.0,
            y: 0.0,
            known: false,
            width,
            height: layer_h,
            fil,
            flow: 1.0,
        };
        for band in &bands {
            pen.out.push_str(&format!(
                "; RETRACT_BAND_START index={} length={:.3} z0={:.3} z1={:.3}\n",
                band.index, band.length, band.z0, band.z1
            ));
            let first_layer = ((band.z0 / layer_h).round() as usize).saturating_sub(1);
            let last_layer = (band.z1 / layer_h).round() as usize;
            for layer_i in first_layer..last_layer {
                let z = (layer_i as f64 + 1.0) * layer_h;
                pen.out.push_str(&format!(
                    ";LAYER:{layer_i} Z:{z:.3} H:{layer_h:.3} length={:.3}\n",
                    band.length
                ));
                pen.out.push_str(&format!("G1 Z{z:.3} F7200\n"));
                pen.layer_fan(layer_i);
                pen.comment("TYPE:RETRACT_POST");
                pen.filament(-band.length, retract_speed);
                pen.travel(ax, ay, 120.0);
                pen.filament(band.length, retract_speed);
                pen.extrude(ax + side, ay, speed);
                pen.extrude(ax + side, ay + side, speed);
                pen.extrude(ax, ay + side, speed);
                pen.extrude(ax, ay, speed);
                pen.filament(-band.length, retract_speed);
                pen.travel(bx, by, 120.0);
                pen.filament(band.length, retract_speed);
                pen.extrude(bx + side, by, speed);
                pen.extrude(bx + side, by + side, speed);
                pen.extrude(bx, by + side, speed);
                pen.extrude(bx, by, speed);
            }
        }
        pen.e
    };
    let z_park = bands.last().unwrap().z1 + 10.0;
    let parked = e - 1.0;
    out.push_str(&format!("G1 E{parked:.5} F1800\n"));
    out.push_str(&format!("G1 Z{z_park:.3} F600\n"));
    out.push_str(&format!("; FILAMENT_E:{e:.3}\n"));
    out.push_str("M106 S0\nM104 S0\nM140 S0\nM84\n");
    Ok(RetractCalibOutput {
        gcode: out,
        bands,
        final_e: e,
        speed_mm_s: retract_speed,
    })
}

struct Pen<'a> {
    out: &'a mut String,
    e: f64,
    x: f64,
    y: f64,
    known: bool,
    width: f64,
    height: f64,
    fil: f64,
    flow: f64,
}

impl Pen<'_> {
    fn comment(&mut self, text: &str) {
        self.out.push_str("; ");
        self.out.push_str(text);
        self.out.push('\n');
    }

    fn travel(&mut self, x: f64, y: f64, speed: f64) {
        let f = (speed * 60.0).round() as i32;
        self.out.push_str(&format!("G1 X{x:.3} Y{y:.3} F{f}\n"));
        self.x = x;
        self.y = y;
        self.known = true;
    }

    fn extrude(&mut self, x: f64, y: f64, speed: f64) {
        let len = if self.known {
            (x - self.x).hypot(y - self.y)
        } else {
            0.0
        };
        if len < 1e-6 {
            self.travel(x, y, speed);
            return;
        }
        self.e += len * self.width * self.height * self.flow / self.fil;
        let f = (speed * 60.0).round() as i32;
        self.out
            .push_str(&format!("G1 X{x:.3} Y{y:.3} E{:.5} F{f}\n", self.e));
        self.x = x;
        self.y = y;
        self.known = true;
    }

    /// The fan a slice runs: off on the first layer, half on the second,
    /// full from the third.
    fn layer_fan(&mut self, layer: usize) {
        match layer {
            0 => self.out.push_str("M106 S0\n"),
            1 => self.out.push_str("M106 S128\n"),
            2 => self.out.push_str("M106 S255\n"),
            _ => {}
        }
    }

    /// A pure filament move. Negative `delta` retracts.
    fn filament(&mut self, delta: f64, speed: f64) {
        if delta.abs() < 1e-9 {
            return;
        }
        self.e += delta;
        let f = (speed * 60.0).round() as i32;
        self.out.push_str(&format!("G1 E{:.5} F{f}\n", self.e));
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn ks(gcode: &str) -> Vec<f64> {
        gcode
            .lines()
            .filter_map(|l| l.strip_prefix("SET_PRESSURE_ADVANCE ADVANCE="))
            .filter_map(|v| v.parse().ok())
            .collect()
    }

    /// The command lines after `;LAYER:{n} `, up to the next layer.
    fn layer_lines(gcode: &str, n: usize) -> Vec<&str> {
        gcode
            .lines()
            .skip_while(|l| !l.starts_with(&format!(";LAYER:{n} ")))
            .skip(1)
            .take_while(|l| !l.starts_with(";LAYER:"))
            .collect()
    }

    #[test]
    fn towers_ramp_the_fan_like_a_slice() {
        let towers = [
            (
                "pa",
                pressure_advance_tower(&PaCalib::default()).unwrap().gcode,
            ),
            ("flow", flow_tower(&FlowCalib::default()).unwrap().gcode),
            (
                "temp",
                temperature_tower(&TempCalib::default()).unwrap().gcode,
            ),
            (
                "retract",
                retract_tower(&RetractCalib::default()).unwrap().gcode,
            ),
        ];
        for (name, gcode) in &towers {
            assert!(
                !layer_lines(gcode, 0)
                    .iter()
                    .any(|l| l.starts_with("M106 S") && *l != "M106 S0"),
                "{name}: fan on layer 0"
            );
            assert!(
                layer_lines(gcode, 1).contains(&"M106 S128"),
                "{name}: layer 1 is not at half fan"
            );
            assert!(
                layer_lines(gcode, 2).contains(&"M106 S255"),
                "{name}: layer 2 is not at full fan"
            );
            assert!(
                gcode.contains("M106 S0\nM104 S0\nM140 S0\n"),
                "{name}: fan left on at the end"
            );
        }
    }

    #[test]
    fn the_temperature_tower_waits_with_the_nozzle_off_the_part() {
        let out = temperature_tower(&TempCalib::default()).unwrap();
        let body = &out.gcode[out.gcode.find("G28").unwrap()..];
        let mut z = 0.0;
        let mut waits = 0;
        let mut top = 0.0_f64;
        for line in body.lines() {
            if let Some(v) = line
                .strip_prefix("G1 ")
                .and_then(|m| m.split_whitespace().find_map(|w| w.strip_prefix('Z')))
            {
                z = v.parse().unwrap();
            }
            if line.starts_with("G1 ") && line.contains(" E") && line.contains(" X") {
                top = top.max(z);
            }
            // The first band waits before anything is printed.
            if line.starts_with("M109 ") && top > 0.0 {
                waits += 1;
                assert!(
                    z >= top + 2.0,
                    "M109 at Z{z} over a tower printed to Z{top}"
                );
            }
        }
        assert!(waits > 0, "no wait over the printed tower");
    }

    #[test]
    fn a_printer_slower_than_10_mm_s_at_the_bead_still_gets_towers() {
        // 0.5 mm^3/s over a 0.45 x 0.2 mm bead caps the feed at 5.6 mm/s.
        let profile = PrinterProfile {
            max_volumetric_mm3_s: 0.5,
            ..PrinterProfile::default()
        };
        let feeds = |gcode: &str| -> (f64, f64) {
            gcode
                .lines()
                .filter(|l| l.starts_with("G1 ") && l.contains(" E") && l.contains(" X"))
                .filter_map(|l| l.split_whitespace().find_map(|w| w.strip_prefix('F')?.parse().ok()))
                .fold((f64::INFINITY, 0.0), |(lo, hi), f: f64| (lo.min(f), hi.max(f)))
        };
        let pa = pressure_advance_tower(&PaCalib {
            profile: profile.clone(),
            ..PaCalib::default()
        })
        .unwrap();
        let flow = flow_tower(&FlowCalib {
            profile: profile.clone(),
            ..FlowCalib::default()
        })
        .unwrap();
        let temp = temperature_tower(&TempCalib {
            profile,
            ..TempCalib::default()
        })
        .unwrap();
        for (name, gcode) in [("flow", &flow.gcode), ("temp", &temp.gcode)] {
            let (_, top) = feeds(gcode);
            assert!(top > 0.0 && top <= 5.6 * 60.0, "{name}: fastest print feed F{top}");
        }
        // The fast pass keeps its 5 mm/s over the slow one, as it always has.
        let (slow, _) = feeds(&pa.gcode);
        assert!(slow <= 5.6 * 60.0, "pa: slowest print feed F{slow}");
    }

    #[test]
    fn klipper_bands_step_and_sit_at_the_right_z() {
        let out = pressure_advance_tower(&PaCalib {
            end: 0.04,
            step: 0.02,
            band_height: 1.0,
            ..PaCalib::default()
        })
        .unwrap();
        let values = ks(&out.gcode);
        assert_eq!(values, vec![0.0, 0.02, 0.04]);
        assert_eq!(out.bands.len(), 3);
        assert!((out.bands[0].z0 - 0.2).abs() < 1e-6);
        assert!((out.bands[0].z1 - 1.0).abs() < 1e-6);
        assert!((out.bands[1].z0 - 1.2).abs() < 1e-6);
        assert!((out.bands[2].z1 - 3.0).abs() < 1e-6);
        assert!(out.final_e > 10.0 && out.final_e < 500.0, "E {}", out.final_e);
        assert!(out.gcode.contains("TYPE:PA_FAST"));
        assert!(out.gcode.contains("F2400"), "slow 40 mm/s");
        assert!(out.fast_mm_s > out.slow_mm_s + 20.0);
        let fast_f = format!("F{}", (out.fast_mm_s * 60.0).round() as i32);
        assert!(out.gcode.contains(&fast_f));
        // Every band's layers fall inside its Z window.
        let mut band_i = 0usize;
        for line in out.gcode.lines() {
            if let Some(rest) = line.strip_prefix(";LAYER:") {
                let mut z = 0.0;
                for tok in rest.split_whitespace() {
                    if let Some(v) = tok.strip_prefix("Z:") {
                        z = v.parse().unwrap();
                    }
                }
                let band = &out.bands[band_i.min(out.bands.len() - 1)];
                if z > band.z1 + 1e-6 {
                    band_i += 1;
                }
                let band = &out.bands[band_i];
                assert!(
                    z + 1e-6 >= band.z0 && z <= band.z1 + 1e-6,
                    "layer Z {z} outside band {} {:.3}..{:.3}",
                    band.index,
                    band.z0,
                    band.z1
                );
            }
        }
    }

    #[test]
    fn marlin_emits_m900_and_rejects_a_bad_range() {
        let out = pressure_advance_tower(&PaCalib {
            firmware: PaFirmware::Marlin,
            start: 0.1,
            end: 0.3,
            step: 0.1,
            band_height: 0.4,
            ..PaCalib::default()
        })
        .unwrap();
        assert!(out.gcode.contains("M900 K0.1000"));
        assert!(out.gcode.contains("M900 K0.2000"));
        assert!(out.gcode.contains("M900 K0.3000"));
        assert!(!out.gcode.contains("SET_PRESSURE_ADVANCE"));
        assert!(pressure_advance_tower(&PaCalib {
            end: 0.0,
            start: 0.1,
            ..PaCalib::default()
        })
        .is_err());
    }

    fn first_extrude_e(gcode: &str) -> f64 {
        gcode
            .lines()
            .find_map(|line| {
                if !line.starts_with("G1 ") || !line.contains(" E") {
                    return None;
                }
                line.split_whitespace()
                    .find_map(|tok| tok.strip_prefix('E')?.parse().ok())
            })
            .unwrap()
    }

    #[test]
    fn flow_bands_scale_extrusion_and_skip_m221() {
        let out = flow_tower(&FlowCalib {
            start: 0.9,
            end: 1.1,
            step: 0.1,
            band_height: 0.4,
            ..FlowCalib::default()
        })
        .unwrap();
        let values: Vec<f64> = out.bands.iter().map(|b| b.flow).collect();
        assert_eq!(values, vec![0.9, 1.0, 1.1]);
        assert!((out.bands[0].z0 - 0.2).abs() < 1e-6);
        assert!((out.bands[0].z1 - 0.4).abs() < 1e-6);
        assert!(out.gcode.contains("TYPE:FLOW_WALL"));
        assert!(!out.gcode.contains("M221"));
        let one = flow_tower(&FlowCalib {
            start: 1.0,
            end: 1.0,
            step: 0.05,
            band_height: 0.2,
            ..FlowCalib::default()
        })
        .unwrap();
        let up = flow_tower(&FlowCalib {
            start: 1.1,
            end: 1.1,
            step: 0.05,
            band_height: 0.2,
            ..FlowCalib::default()
        })
        .unwrap();
        let ratio = up.final_e / one.final_e;
        assert!((ratio - 1.1).abs() < 1e-9, "ratio {ratio}");
        let printed = first_extrude_e(&up.gcode) / first_extrude_e(&one.gcode);
        assert!((printed - 1.1).abs() < 1e-4, "printed {printed}");
        assert!(flow_tower(&FlowCalib {
            start: 1.2,
            end: 0.9,
            ..FlowCalib::default()
        })
        .is_err());
        assert!(flow_tower(&FlowCalib {
            start: 0.2,
            end: 0.4,
            step: 0.1,
            ..FlowCalib::default()
        })
        .is_err());
    }

    #[test]
    fn temperature_bands_wait_and_reject_a_cold_start() {
        let out = temperature_tower(&TempCalib {
            start: 200.0,
            end: 220.0,
            step: 10.0,
            band_height: 0.4,
            ..TempCalib::default()
        })
        .unwrap();
        let temps: Vec<f64> = out.bands.iter().map(|b| b.temp).collect();
        assert_eq!(temps, vec![200.0, 210.0, 220.0]);
        assert!(out.gcode.contains("M109 S200"));
        assert!(out.gcode.contains("M109 S210"));
        assert!(out.gcode.contains("M109 S220"));
        assert!(out.gcode.contains("TYPE:TEMP_WALL"));
        assert!((out.bands[0].z0 - 0.2).abs() < 1e-6);
        assert!(temperature_tower(&TempCalib {
            start: 100.0,
            end: 140.0,
            step: 10.0,
            ..TempCalib::default()
        })
        .is_err());
        assert!(temperature_tower(&TempCalib {
            start: 220.0,
            end: 200.0,
            ..TempCalib::default()
        })
        .is_err());
    }

    #[test]
    fn retract_bands_pull_between_posts() {
        let out = retract_tower(&RetractCalib {
            start: 0.4,
            end: 0.8,
            step: 0.2,
            band_height: 0.2,
            speed_mm_s: 45.0,
            ..RetractCalib::default()
        })
        .unwrap();
        let lengths: Vec<f64> = out.bands.iter().map(|b| b.length).collect();
        assert_eq!(lengths, vec![0.4, 0.6, 0.8]);
        assert!(out.gcode.contains("TYPE:RETRACT_POST"));
        assert!(out.gcode.contains("F2700"));
        assert!(out.gcode.contains("G1 E"));
        assert!(retract_tower(&RetractCalib {
            start: 1.0,
            end: 0.2,
            ..RetractCalib::default()
        })
        .is_err());
        assert!(retract_tower(&RetractCalib {
            speed_mm_s: 1.0,
            ..RetractCalib::default()
        })
        .is_err());
    }
}
