use crate::strategy::{BlendMode, PrinterProfile};
use crate::toolpath::Extrusion;

#[derive(Clone, Debug)]
pub struct GcodeStats {
    pub text: String,
    pub extrusion_moves: usize,
    pub travel_moves: usize,
    pub final_e: f64,
    pub min_x: f64,
    pub max_x: f64,
    pub min_y: f64,
    pub max_y: f64,
    pub extrusion_length_mm: f64,
    pub travel_length_mm: f64,
    pub layer_count: usize,
}

pub fn emit_gcode(
    layers: &[LayerPaths],
    profile: &PrinterProfile,
    blend: &BlendMode,
    layer_height: f64,
    line_width: f64,
) -> GcodeStats {
    let mut w = Writer::new(profile, blend, layer_height, line_width);
    let mut emitted_layers = 0usize;
    for layer in layers {
        if layer.paths.is_empty() {
            continue;
        }
        w.layer_header(layer);
        emitted_layers += 1;
        for path in &layer.paths {
            w.set_accel(path.accel);
            if layer.index >= 2 {
                w.set_fan(path.fan);
            } else if layer.index == 1 {
                w.set_fan(128);
            } else {
                w.set_fan(0);
            }
            let speed = if layer.index == 0 {
                path.speed.min(30.0)
            } else {
                path.speed
            };
            let flow = if layer.index == 0 { 1.06 } else { 1.0 };
            w.comment(&format!("TYPE:{}", path.kind.as_str().to_ascii_uppercase()));
            if path.points.is_empty() {
                continue;
            }
            w.travel(
                path.points[0][0],
                path.points[0][1],
                path.travel_speed,
                path.retract_mm,
                path.retract_min_travel,
            );
            for p in path.points.iter().skip(1) {
                w.extrude(
                    p[0],
                    p[1],
                    speed,
                    path.width,
                    layer_height,
                    flow,
                    profile.filament_diameter,
                );
            }
        }
    }
    w.finish(profile);
    w.stats(emitted_layers)
}

pub struct LayerPaths {
    pub index: usize,
    pub z: f64,
    pub paths: Vec<Extrusion>,
    pub note: String,
}

struct Writer {
    out: String,
    e: f64,
    x: f64,
    y: f64,
    z: f64,
    has_pos: bool,
    retracted: f64,
    accel: f64,
    fan: i32,
    extrusion_moves: usize,
    travel_moves: usize,
    min_x: f64,
    max_x: f64,
    min_y: f64,
    max_y: f64,
    extrusion_length_mm: f64,
    travel_length_mm: f64,
    bounds_init: bool,
}

impl Writer {
    fn new(
        profile: &PrinterProfile,
        blend: &BlendMode,
        layer_height: f64,
        line_width: f64,
    ) -> Self {
        let mut out = String::new();
        out.push_str("; generated by Lime Slice — FDM strategy blender\n");
        out.push_str(&format!("; printer: {}\n", profile.name));
        out.push_str(&format!("; blend: {}\n", blend.describe()));
        out.push_str(&format!(
            "; layer_height: {layer_height:.3} line_width: {line_width:.3} filament: {:.2}\n",
            profile.filament_diameter
        ));
        out.push_str(&format!("M140 S{:.0}\n", profile.bed_temp));
        out.push_str(&format!("M104 S{:.0}\n", profile.nozzle_temp));
        out.push_str(&format!("M190 S{:.0}\n", profile.bed_temp));
        out.push_str(&format!("M109 S{:.0}\n", profile.nozzle_temp));
        out.push_str("G21\nG90\nM82\nG28\nG92 E0\nM106 S0\nM204 S1500\n");
        Self {
            out,
            e: 0.0,
            x: 0.0,
            y: 0.0,
            z: 0.0,
            has_pos: false,
            retracted: 0.0,
            accel: 1500.0,
            fan: 0,
            extrusion_moves: 0,
            travel_moves: 0,
            min_x: 0.0,
            max_x: 0.0,
            min_y: 0.0,
            max_y: 0.0,
            extrusion_length_mm: 0.0,
            travel_length_mm: 0.0,
            bounds_init: false,
        }
    }

    fn comment(&mut self, text: &str) {
        self.out.push_str("; ");
        self.out.push_str(text);
        self.out.push('\n');
    }

    fn layer_header(&mut self, layer: &LayerPaths) {
        self.out.push_str(&format!(
            ";LAYER:{} Z:{:.3} {}\n",
            layer.index, layer.z, layer.note
        ));
        let f = (120.0_f64 * 60.0) as i32;
        self.out.push_str(&format!("G1 Z{:.3} F{f}\n", layer.z));
        self.z = layer.z;
    }

    fn set_accel(&mut self, accel: f64) {
        let accel = accel.round();
        if (accel - self.accel).abs() < 1.0 {
            return;
        }
        self.accel = accel;
        self.out.push_str(&format!("M204 S{:.0}\n", accel));
    }

    fn set_fan(&mut self, pwm: u8) {
        let pwm = pwm as i32;
        if pwm == self.fan {
            return;
        }
        self.fan = pwm;
        self.out.push_str(&format!("M106 S{pwm}\n"));
    }

    fn unretract(&mut self) {
        if self.retracted > 0.0 {
            self.e += self.retracted;
            self.retracted = 0.0;
            self.out.push_str(&format!("G1 E{:.5} F1800\n", self.e));
        }
    }

    fn travel(&mut self, x: f64, y: f64, speed: f64, retract_mm: f64, min_travel: f64) {
        if self.has_pos {
            let d = hypot(x - self.x, y - self.y);
            if d < 0.02 {
                return;
            }
            if d >= min_travel && retract_mm > 0.0 && self.retracted == 0.0 {
                self.e -= retract_mm;
                self.retracted = retract_mm;
                self.out.push_str(&format!("G1 E{:.5} F1800\n", self.e));
            }
            self.travel_length_mm += d;
        }
        self.unretract();
        let f = (speed.max(10.0) * 60.0).round() as i32;
        self.out.push_str(&format!("G1 X{:.3} Y{:.3} F{f}\n", x, y));
        self.x = x;
        self.y = y;
        self.has_pos = true;
        self.travel_moves += 1;
    }

    fn extrude(
        &mut self,
        x: f64,
        y: f64,
        speed: f64,
        width: f64,
        layer_h: f64,
        flow: f64,
        filament_d: f64,
    ) {
        self.unretract();
        let d = hypot(x - self.x, y - self.y);
        if d < 1e-4 {
            return;
        }
        let bead = width * layer_h * flow;
        let fil = std::f64::consts::PI * (filament_d * 0.5).powi(2);
        self.e += d * bead / fil;
        let f = (speed.max(5.0) * 60.0).round() as i32;
        self.out
            .push_str(&format!("G1 X{:.3} Y{:.3} E{:.5} F{f}\n", x, y, self.e));
        self.note_bounds(x, y);
        self.x = x;
        self.y = y;
        self.has_pos = true;
        self.extrusion_moves += 1;
        self.extrusion_length_mm += d;
    }

    fn note_bounds(&mut self, x: f64, y: f64) {
        if !self.bounds_init {
            self.min_x = x;
            self.max_x = x;
            self.min_y = y;
            self.max_y = y;
            self.bounds_init = true;
            return;
        }
        self.min_x = self.min_x.min(x);
        self.max_x = self.max_x.max(x);
        self.min_y = self.min_y.min(y);
        self.max_y = self.max_y.max(y);
    }

    fn finish(&mut self, profile: &PrinterProfile) {
        if self.has_pos && self.retracted == 0.0 {
            self.e -= 1.0;
            self.retracted = 1.0;
            self.out.push_str(&format!("G1 E{:.5} F1800\n", self.e));
        }
        let z = self.z + 10.0;
        self.out.push_str(&format!("G1 Z{:.3} F600\n", z));
        self.out.push_str("M106 S0\n");
        self.out.push_str(&format!("M104 S0\nM140 S0\n"));
        self.out.push_str(&format!(
            "; bed {}x{} mm nozzle {:.2} mm\n",
            profile.bed_x, profile.bed_y, profile.nozzle_diameter
        ));
        self.out.push_str("M84\n");
    }

    fn stats(self, layer_count: usize) -> GcodeStats {
        GcodeStats {
            final_e: self.e + self.retracted,
            text: self.out,
            extrusion_moves: self.extrusion_moves,
            travel_moves: self.travel_moves,
            min_x: self.min_x,
            max_x: self.max_x,
            min_y: self.min_y,
            max_y: self.max_y,
            extrusion_length_mm: self.extrusion_length_mm,
            travel_length_mm: self.travel_length_mm,
            layer_count,
        }
    }
}

fn hypot(x: f64, y: f64) -> f64 {
    x.hypot(y)
}
