use crate::strategy::{BlendMode, PrinterProfile};
use crate::toolpath::Extrusion;

#[derive(Clone, Debug)]
pub struct GcodeStats {
    pub text: String,
    pub extrusion_moves: usize,
    pub travel_moves: usize,
    pub final_e: f64,
    pub min_x: f64,
    pub max_x: f64,
    pub min_y: f64,
    pub max_y: f64,
    pub extrusion_length_mm: f64,
    pub travel_length_mm: f64,
    pub layer_count: usize,
    pub print_time_s: f64,
    pub filament_mm: f64,
    pub filament_g: f64,
    pub arc_moves: usize,
    pub retracts: usize,
    pub z_hops: usize,
}

pub fn emit_gcode(
    layers: &[LayerPaths],
    profile: &PrinterProfile,
    blend: &BlendMode,
    layer_height: f64,
    line_width: f64,
    features: &str,
    arc_fit: bool,
) -> GcodeStats {
    let mut w = Writer::new(profile, blend, layer_height, line_width, features);
    let mut emitted_layers = 0usize;
    for layer in layers {
        if layer.paths.is_empty() {
            continue;
        }
        w.layer_header(layer);
        emitted_layers += 1;
        for path in &layer.paths {
            w.set_advance(path.kind.as_str());
            if layer.index >= 2 {
                w.set_fan(path.fan);
            } else if layer.index == 1 {
                w.set_fan(128);
            } else {
                w.set_fan(0);
            }
            let speed = if layer.index == 0 {
                path.speed.min(30.0)
            } else {
                path.speed
            };
            let flow = if layer.index == 0 { 1.06 } else { 1.0 };
            w.comment(&format!("TYPE:{}", path.kind.as_str().to_ascii_uppercase()));
            if path.points.is_empty() {
                continue;
            }
            let bead_h = if path.bead_height > 1e-6 {
                path.bead_height
            } else {
                layer.height
            };
            w.set_accel(path.travel_accel);
            let mut hop = path.lead_in.clone();
            hop.push(path.points[0]);
            w.travel_chain(
                &hop,
                path.travel_speed,
                path.retract_mm,
                path.retract_min_travel,
                path.travel_accel,
                path.z_hop,
                layer.z,
            );
            w.set_accel(path.accel);
            let limited = limit_speed(
                speed,
                path.width,
                bead_h,
                flow * path.flow,
                profile.max_volumetric_mm3_s,
            );
            let fit = arc_fit
                && (path.fit_arcs
                    || matches!(
                        path.kind,
                        crate::toolpath::PathKind::Wall
                            | crate::toolpath::PathKind::Outer
                            | crate::toolpath::PathKind::Inner
                            | crate::toolpath::PathKind::ThinWall
                            | crate::toolpath::PathKind::Skirt
                    ));
            w.emit_chain(
                &path.points,
                limited,
                path.width,
                bead_h,
                flow * path.flow,
                profile.filament_diameter,
                path.accel,
                fit,
                &path.z_frac,
                &path.flow_frac,
                layer.z,
                layer.height,
            );
        }
    }
    w.finish(profile);
    w.stats(emitted_layers, profile)
}

pub struct LayerPaths {
    pub index: usize,
    pub z: f64,
    pub height: f64,
    pub paths: Vec<Extrusion>,
    pub note: String,
}

struct Writer {
    out: String,
    e: f64,
    x: f64,
    y: f64,
    z: f64,
    has_pos: bool,
    retracted: f64,
    accel: f64,
    fan: i32,
    extrusion_moves: usize,
    travel_moves: usize,
    min_x: f64,
    max_x: f64,
    min_y: f64,
    max_y: f64,
    extrusion_length_mm: f64,
    travel_length_mm: f64,
    bounds_init: bool,
    time_s: f64,
    arc_moves: usize,
    retracts: usize,
    z_hops: usize,
    dir: [f64; 2],
    has_dir: bool,
    pa_base: f64,
    la_base: f64,
    pa_cur: f64,
    la_cur: f64,
    emit_pa: bool,
}

impl Writer {
    fn new(
        profile: &PrinterProfile,
        blend: &BlendMode,
        layer_height: f64,
        line_width: f64,
        features: &str,
    ) -> Self {
        let mut out = String::new();
        out.push_str("; generated by Lime Slice — FDM strategy blender\n");
        out.push_str(&format!("; printer: {}\n", profile.name));
        out.push_str(&format!("; blend: {}\n", blend.describe()));
        out.push_str(&format!(
            "; layer_height: {layer_height:.3} line_width: {line_width:.3} filament: {:.2}\n",
            profile.filament_diameter
        ));
        out.push_str(&format!("; features: {features}\n"));
        out.push_str(&format!("M140 S{:.0}\n", profile.bed_temp));
        out.push_str(&format!("M104 S{:.0}\n", profile.nozzle_temp));
        out.push_str(&format!("M190 S{:.0}\n", profile.bed_temp));
        out.push_str(&format!("M109 S{:.0}\n", profile.nozzle_temp));
        out.push_str("G21\nG90\nM82\nG28\nG92 E0\nM106 S0\nM204 S1500\n");
        if profile.pressure_advance > 0.0 {
            out.push_str(&format!(
                "SET_PRESSURE_ADVANCE ADVANCE={:.4}\n",
                profile.pressure_advance
            ));
        }
        if profile.linear_advance > 0.0 {
            out.push_str(&format!("M900 K{:.3}\n", profile.linear_advance));
        }
        Self {
            out,
            e: 0.0,
            x: 0.0,
            y: 0.0,
            z: 0.0,
            has_pos: false,
            retracted: 0.0,
            accel: 1500.0,
            fan: 0,
            extrusion_moves: 0,
            travel_moves: 0,
            min_x: 0.0,
            max_x: 0.0,
            min_y: 0.0,
            max_y: 0.0,
            extrusion_length_mm: 0.0,
            travel_length_mm: 0.0,
            bounds_init: false,
            time_s: 0.0,
            arc_moves: 0,
            retracts: 0,
            z_hops: 0,
            dir: [1.0, 0.0],
            has_dir: false,
            pa_base: profile.pressure_advance.max(0.0),
            la_base: profile.linear_advance.max(0.0),
            pa_cur: profile.pressure_advance.max(0.0),
            la_cur: profile.linear_advance.max(0.0),
            emit_pa: profile.pressure_advance > 0.0 || profile.linear_advance > 0.0,
        }
    }

    fn set_advance(&mut self, kind: &str) {
        if !self.emit_pa {
            return;
        }
        let scale = crate::strategy::advance_scale(kind);
        let pa = self.pa_base * scale;
        let la = self.la_base * scale;
        if self.pa_base > 0.0 && (pa - self.pa_cur).abs() > 1e-4 {
            self.out
                .push_str(&format!("SET_PRESSURE_ADVANCE ADVANCE={pa:.4}\n"));
            self.pa_cur = pa;
        }
        if self.la_base > 0.0 && (la - self.la_cur).abs() > 1e-4 {
            self.out.push_str(&format!("M900 K{la:.3}\n"));
            self.la_cur = la;
        }
    }

    fn comment(&mut self, text: &str) {
        self.out.push_str("; ");
        self.out.push_str(text);
        self.out.push('\n');
    }

    fn layer_header(&mut self, layer: &LayerPaths) {
        self.out.push_str(&format!(
            ";LAYER:{} Z:{:.3} H:{:.3} {}\n",
            layer.index, layer.z, layer.height, layer.note
        ));
        let dz = (layer.z - self.z).abs();
        let f = (120.0_f64 * 60.0) as i32;
        self.out.push_str(&format!("G1 Z{:.3} F{f}\n", layer.z));
        if dz > 1e-6 {
            self.time_s += dz / 120.0;
        }
        self.z = layer.z;
        self.has_dir = false;
    }

    fn set_accel(&mut self, accel: f64) {
        let accel = accel.round();
        if (accel - self.accel).abs() < 1.0 {
            return;
        }
        self.accel = accel;
        self.out.push_str(&format!("M204 S{accel:.0}\n"));
    }

    fn set_fan(&mut self, pwm: u8) {
        let pwm = pwm as i32;
        if pwm == self.fan {
            return;
        }
        self.fan = pwm;
        self.out.push_str(&format!("M106 S{pwm}\n"));
    }

    fn unretract(&mut self) {
        if self.retracted > 0.0 {
            self.e += self.retracted;
            let feed = self.retracted;
            self.retracted = 0.0;
            self.out.push_str(&format!("G1 E{:.5} F1800\n", self.e));
            self.time_s += feed / 30.0;
        }
    }

    #[allow(clippy::too_many_arguments)]
    fn travel_chain(
        &mut self,
        pts: &[[f64; 2]],
        speed: f64,
        retract_mm: f64,
        min_travel: f64,
        accel: f64,
        z_hop: f64,
        layer_z: f64,
    ) {
        if z_hop > 1e-6 && self.has_pos {
            let mut full = Vec::with_capacity(pts.len() + 1);
            full.push([self.x, self.y]);
            full.extend(pts.iter().copied());
            let total: f64 = full
                .windows(2)
                .map(|w| hypot(w[1][0] - w[0][0], w[1][1] - w[0][1]))
                .sum();
            if total >= 0.02 {
                self.hop_travel(&full, speed, retract_mm, accel, z_hop, layer_z, total);
                return;
            }
        }
        for (i, p) in pts.iter().enumerate() {
            let retract = if i == 0 { retract_mm } else { 0.0 };
            self.travel_one(p[0], p[1], speed, retract, min_travel, accel);
        }
    }

    /// Retract, slope up to `layer_z + z_hop` along the travel, then slope back
    /// to the layer before the next extrusion. A short hop lifts vertically.
    #[allow(clippy::too_many_arguments)]
    fn hop_travel(
        &mut self,
        pts: &[[f64; 2]],
        speed: f64,
        retract_mm: f64,
        accel: f64,
        z_hop: f64,
        layer_z: f64,
        total: f64,
    ) {
        if retract_mm > 0.0 && self.retracted == 0.0 {
            self.e -= retract_mm;
            self.retracted = retract_mm;
            self.retracts += 1;
            self.out.push_str(&format!("G1 E{:.5} F1800\n", self.e));
            self.time_s += retract_mm / 30.0;
        }
        self.z_hops += 1;
        let ramp = (z_hop * 4.0).clamp(0.6, 2.5).min(total * 0.45);
        if total < ramp * 2.2 {
            self.set_z(layer_z + z_hop);
            for p in pts {
                self.travel_dry(p[0], p[1], speed, accel);
            }
            self.set_z(layer_z);
        } else {
            self.slope_along(pts, speed, accel, layer_z, z_hop, ramp, total);
        }
        self.unretract();
    }

    #[allow(clippy::too_many_arguments)]
    fn slope_along(
        &mut self,
        pts: &[[f64; 2]],
        speed: f64,
        accel: f64,
        layer_z: f64,
        z_hop: f64,
        ramp: f64,
        total: f64,
    ) {
        let mut walked = 0.0;
        for w in pts.windows(2) {
            let seg = hypot(w[1][0] - w[0][0], w[1][1] - w[0][1]);
            if seg < 1e-6 {
                continue;
            }
            let mut left = seg;
            let mut a = w[0];
            while left > 1e-4 {
                let dist = walked;
                let z_here = hop_height(dist, total, ramp, layer_z, z_hop);
                let next_mark = if dist < ramp {
                    ramp
                } else if dist < total - ramp {
                    total - ramp
                } else {
                    total
                };
                let step = (next_mark - dist).max(0.05).min(left);
                let _ = z_here;
                let b = [
                    a[0] + (w[1][0] - a[0]) * (step / left),
                    a[1] + (w[1][1] - a[1]) * (step / left),
                ];
                let z_next = hop_height(dist + step, total, ramp, layer_z, z_hop);
                self.travel_dry_z(b[0], b[1], z_next, speed, accel);
                walked += step;
                left -= step;
                a = b;
            }
        }
        self.set_z(layer_z);
    }

    fn travel_dry(&mut self, x: f64, y: f64, speed: f64, accel: f64) {
        self.travel_dry_z(x, y, self.z, speed, accel);
    }

    fn travel_dry_z(&mut self, x: f64, y: f64, z: f64, speed: f64, accel: f64) {
        if !self.has_pos {
            self.x = x;
            self.y = y;
            self.z = z;
            self.has_pos = true;
            return;
        }
        let d = hypot(x - self.x, y - self.y);
        let dz = (z - self.z).abs();
        if d < 0.02 && dz < 5e-4 {
            return;
        }
        self.travel_length_mm += d;
        self.time_s += move_time((d * d + dz * dz).sqrt(), 0.0, 0.0, speed.max(10.0), accel);
        let f = (speed.max(10.0) * 60.0).round() as i32;
        if dz > 5e-4 {
            self.out
                .push_str(&format!("G1 X{x:.3} Y{y:.3} Z{z:.3} F{f}\n"));
            self.z = z;
        } else {
            self.out.push_str(&format!("G1 X{x:.3} Y{y:.3} F{f}\n"));
        }
        self.x = x;
        self.y = y;
        self.has_pos = true;
        self.has_dir = false;
        self.travel_moves += 1;
    }

    fn travel_one(
        &mut self,
        x: f64,
        y: f64,
        speed: f64,
        retract_mm: f64,
        min_travel: f64,
        accel: f64,
    ) {
        if self.has_pos {
            let d = hypot(x - self.x, y - self.y);
            if d < 0.02 {
                return;
            }
            if d >= min_travel && retract_mm > 0.0 && self.retracted == 0.0 {
                self.e -= retract_mm;
                self.retracted = retract_mm;
                self.retracts += 1;
                self.out.push_str(&format!("G1 E{:.5} F1800\n", self.e));
                self.time_s += retract_mm / 30.0;
            }
            self.travel_length_mm += d;
            self.time_s += move_time(d, 0.0, 0.0, speed.max(10.0), accel);
            self.has_dir = false;
        }
        self.unretract();
        let f = (speed.max(10.0) * 60.0).round() as i32;
        self.out.push_str(&format!("G1 X{x:.3} Y{y:.3} F{f}\n"));
        self.x = x;
        self.y = y;
        self.has_pos = true;
        self.travel_moves += 1;
    }

    #[allow(clippy::too_many_arguments)]
    fn emit_chain(
        &mut self,
        points: &[[f64; 2]],
        speed: f64,
        width: f64,
        layer_h: f64,
        flow: f64,
        filament_d: f64,
        accel: f64,
        arc_fit: bool,
        z_frac: &[f64],
        flow_frac: &[f64],
        layer_z: f64,
        nominal_h: f64,
    ) {
        if points.len() < 2 {
            return;
        }
        let scarfed = z_frac.len() == points.len() && flow_frac.len() == points.len();
        if scarfed {
            self.set_z(nozzle_z(layer_z, nominal_h, z_frac[0]));
        }
        let mut i = 0usize;
        while i + 1 < points.len() {
            let mut end = i + 1;
            if arc_fit && i + 3 < points.len() && span_planar(z_frac, flow_frac, i, i + 4) {
                let mut j = i + 3;
                while j < points.len() && j - i <= 32 && span_planar(z_frac, flow_frac, i, j + 1) {
                    if fit_arc(&points[i..=j], 0.07).is_some() {
                        end = j;
                        j += 1;
                    } else {
                        break;
                    }
                }
            }
            if end >= i + 3 && span_planar(z_frac, flow_frac, i, end + 1) {
                if let Some(arc) = fit_arc(&points[i..=end], 0.07) {
                    let h = if scarfed {
                        layer_h * z_frac[i].clamp(0.0, 1.0)
                    } else {
                        layer_h
                    };
                    self.arc(arc, speed, width, h, flow, filament_d, accel);
                    i = end;
                    continue;
                }
            }
            let p = points[i + 1];
            let (h, seg_flow, z) = if scarfed {
                let z0 = z_frac[i].clamp(0.0, 1.0);
                let z1 = z_frac[i + 1].clamp(0.0, 1.0);
                let f0 = flow_frac[i].clamp(0.0, 2.0);
                let f1 = flow_frac[i + 1].clamp(0.0, 2.0);
                (
                    nominal_h * 0.5 * (z0 + z1),
                    flow * 0.5 * (f0 + f1),
                    Some(nozzle_z(layer_z, nominal_h, z1)),
                )
            } else {
                (layer_h, flow, None)
            };
            self.extrude(p[0], p[1], speed, width, h, seg_flow, filament_d, accel, z);
            i += 1;
        }
        if scarfed {
            self.set_z(layer_z);
        }
    }

    fn set_z(&mut self, z: f64) {
        if (z - self.z).abs() < 5e-4 {
            return;
        }
        let dz = (z - self.z).abs();
        let f = (120.0_f64 * 60.0) as i32;
        self.out.push_str(&format!("G1 Z{z:.3} F{f}\n"));
        self.time_s += dz / 120.0;
        self.z = z;
    }

    #[allow(clippy::too_many_arguments)]
    fn arc(
        &mut self,
        arc: ArcFit,
        speed: f64,
        width: f64,
        layer_h: f64,
        flow: f64,
        filament_d: f64,
        accel: f64,
    ) {
        self.unretract();
        let bead = width * layer_h * flow;
        let fil = std::f64::consts::PI * (filament_d * 0.5).powi(2);
        self.e += arc.length * bead / fil;
        let f = (speed.max(5.0) * 60.0).round() as i32;
        let cmd = if arc.cw { "G2" } else { "G3" };
        self.out.push_str(&format!(
            "{cmd} X{:.3} Y{:.3} I{:.4} J{:.4} E{:.5} F{f}\n",
            arc.end[0], arc.end[1], arc.ij[0], arc.ij[1], self.e
        ));
        self.note_motion(arc.end, arc.dir, speed, accel, arc.length);
        self.arc_moves += 1;
        self.extrusion_moves += 1;
        self.extrusion_length_mm += arc.length;
    }

    #[allow(clippy::too_many_arguments)]
    fn extrude(
        &mut self,
        x: f64,
        y: f64,
        speed: f64,
        width: f64,
        layer_h: f64,
        flow: f64,
        filament_d: f64,
        accel: f64,
        z: Option<f64>,
    ) {
        self.unretract();
        let d = hypot(x - self.x, y - self.y);
        if d < 1e-4 {
            if let Some(z) = z {
                self.set_z(z);
            }
            return;
        }
        let bead = width * layer_h.max(0.0) * flow.max(0.0);
        let fil = std::f64::consts::PI * (filament_d * 0.5).powi(2);
        self.e += d * bead / fil;
        let f = (speed.max(5.0) * 60.0).round() as i32;
        if let Some(z) = z {
            if (z - self.z).abs() > 5e-4 {
                self.out.push_str(&format!(
                    "G1 X{:.3} Y{:.3} Z{:.3} E{:.5} F{f}\n",
                    x, y, z, self.e
                ));
                self.z = z;
            } else {
                self.out
                    .push_str(&format!("G1 X{:.3} Y{:.3} E{:.5} F{f}\n", x, y, self.e));
            }
        } else {
            self.out
                .push_str(&format!("G1 X{:.3} Y{:.3} E{:.5} F{f}\n", x, y, self.e));
        }
        self.note_motion([x, y], [x - self.x, y - self.y], speed, accel, d);
        self.extrusion_moves += 1;
        self.extrusion_length_mm += d;
    }

    fn note_motion(&mut self, end: [f64; 2], dir: [f64; 2], speed: f64, accel: f64, dist: f64) {
        let v1 = speed.max(5.0);
        let v0 = if self.has_dir {
            let prev = self.dir[0] * dir[0] + self.dir[1] * dir[1];
            let n0 = hypot(self.dir[0], self.dir[1]).max(1e-9);
            let n1 = hypot(dir[0], dir[1]).max(1e-9);
            junction_speed(v1, accel, prev / (n0 * n1))
        } else {
            0.0
        };
        self.time_s += move_time(dist, v0, 0.0, v1, accel);
        self.note_bounds(end[0], end[1]);
        self.x = end[0];
        self.y = end[1];
        self.dir = dir;
        self.has_dir = true;
        self.has_pos = true;
    }

    fn note_bounds(&mut self, x: f64, y: f64) {
        if !self.bounds_init {
            self.min_x = x;
            self.max_x = x;
            self.min_y = y;
            self.max_y = y;
            self.bounds_init = true;
            return;
        }
        self.min_x = self.min_x.min(x);
        self.max_x = self.max_x.max(x);
        self.min_y = self.min_y.min(y);
        self.max_y = self.max_y.max(y);
    }

    fn finish(&mut self, profile: &PrinterProfile) {
        if self.has_pos && self.retracted == 0.0 {
            self.e -= 1.0;
            self.retracted = 1.0;
            self.out.push_str(&format!("G1 E{:.5} F1800\n", self.e));
        }
        let z = self.z + 10.0;
        self.out.push_str(&format!("G1 Z{z:.3} F600\n"));
        self.out.push_str("M106 S0\n");
        self.out.push_str("M104 S0\nM140 S0\n");
        self.out.push_str(&format!(
            "; bed {}x{} mm nozzle {:.2} mm\n",
            profile.bed_x, profile.bed_y, profile.nozzle_diameter
        ));
        let filament_mm = self.e + self.retracted;
        let area = std::f64::consts::PI * (profile.filament_diameter * 0.5).powi(2);
        let filament_g = filament_mm * area * profile.filament_density_g_cm3 / 1000.0;
        self.out.push_str(&format!(
            "; TIME:{:.1}s FILAMENT_MM:{:.2} FILAMENT_G:{:.3} ARCS:{}\n",
            self.time_s, filament_mm, filament_g, self.arc_moves
        ));
        self.out.push_str("M84\n");
    }

    fn stats(self, layer_count: usize, profile: &PrinterProfile) -> GcodeStats {
        let filament_mm = self.e + self.retracted;
        let area = std::f64::consts::PI * (profile.filament_diameter * 0.5).powi(2);
        let filament_g = filament_mm * area * profile.filament_density_g_cm3 / 1000.0;
        GcodeStats {
            final_e: filament_mm,
            print_time_s: self.time_s,
            filament_mm,
            filament_g,
            arc_moves: self.arc_moves,
            retracts: self.retracts,
            z_hops: self.z_hops,
            text: self.out,
            extrusion_moves: self.extrusion_moves,
            travel_moves: self.travel_moves,
            min_x: self.min_x,
            max_x: self.max_x,
            min_y: self.min_y,
            max_y: self.max_y,
            extrusion_length_mm: self.extrusion_length_mm,
            travel_length_mm: self.travel_length_mm,
            layer_count,
        }
    }
}

fn hop_height(dist: f64, total: f64, ramp: f64, layer_z: f64, z_hop: f64) -> f64 {
    let up = (dist / ramp.max(1e-6)).clamp(0.0, 1.0);
    let down = ((total - dist) / ramp.max(1e-6)).clamp(0.0, 1.0);
    layer_z + z_hop * up.min(down)
}

fn hypot(x: f64, y: f64) -> f64 {
    x.hypot(y)
}

fn nozzle_z(layer_z: f64, layer_h: f64, frac: f64) -> f64 {
    let frac = frac.clamp(0.0, 1.0);
    let z = layer_z - layer_h * (1.0 - frac);
    z.clamp(layer_z - layer_h, layer_z)
}

/// A span can be a planar arc only when Z and flow stay constant across it.
fn span_planar(z_frac: &[f64], flow_frac: &[f64], start: usize, end_exclusive: usize) -> bool {
    if z_frac.is_empty() && flow_frac.is_empty() {
        return true;
    }
    if z_frac.is_empty() || flow_frac.is_empty() {
        return false;
    }
    let z0 = z_frac[start];
    let f0 = flow_frac[start];
    (start..end_exclusive).all(|k| {
        z_frac
            .get(k)
            .zip(flow_frac.get(k))
            .map(|(z, f)| (z - z0).abs() < 1e-3 && (f - f0).abs() < 1e-3)
            .unwrap_or(false)
    })
}

fn limit_speed(speed: f64, width: f64, height: f64, flow: f64, max_vol: f64) -> f64 {
    if !max_vol.is_finite() || max_vol <= 0.0 {
        return speed;
    }
    let area = (width * height * flow).max(1e-6);
    speed.min(max_vol / area)
}

fn junction_speed(cruise: f64, accel: f64, cos_theta: f64) -> f64 {
    let sin_half = ((1.0 - cos_theta.clamp(-1.0, 1.0)) * 0.5).max(0.0).sqrt();
    if sin_half < 1e-3 {
        return cruise;
    }
    (accel.max(50.0) * 0.02 / sin_half).sqrt().min(cruise)
}

fn move_time(dist: f64, v0: f64, v1: f64, cruise: f64, accel: f64) -> f64 {
    let a = accel.max(50.0);
    let cruise = cruise.max(v0).max(v1).max(1.0);
    let d_acc = (cruise * cruise - v0 * v0).max(0.0) / (2.0 * a);
    let d_dec = (cruise * cruise - v1 * v1).max(0.0) / (2.0 * a);
    if d_acc + d_dec <= dist {
        (cruise - v0).max(0.0) / a + (cruise - v1).max(0.0) / a + (dist - d_acc - d_dec) / cruise
    } else {
        let peak2 = a * dist + 0.5 * (v0 * v0 + v1 * v1);
        let peak = peak2.max(0.0).sqrt();
        (peak - v0).abs() / a + (peak - v1).abs() / a
    }
}

struct ArcFit {
    end: [f64; 2],
    ij: [f64; 2],
    cw: bool,
    length: f64,
    dir: [f64; 2],
}

fn fit_arc(pts: &[[f64; 2]], tol: f64) -> Option<ArcFit> {
    if pts.len() < 4 {
        return None;
    }
    let a = pts[0];
    let mid = pts[pts.len() / 2];
    let c = *pts.last().unwrap();
    let center = circumcenter(a, mid, c)?;
    let r = hypot(a[0] - center[0], a[1] - center[1]);
    if !(0.8..=140.0).contains(&r) {
        return None;
    }
    for p in pts {
        let d = hypot(p[0] - center[0], p[1] - center[1]);
        if (d - r).abs() > tol {
            return None;
        }
    }
    let a0 = (a[1] - center[1]).atan2(a[0] - center[0]);
    let am = (mid[1] - center[1]).atan2(mid[0] - center[0]);
    let a1 = (c[1] - center[1]).atan2(c[0] - center[0]);
    let cw = sweep(a0, am) < 0.0;
    let mut prev = a0;
    for p in pts.iter().skip(1) {
        let ang = (p[1] - center[1]).atan2(p[0] - center[0]);
        let step = sweep(prev, ang);
        if cw && step > 0.05 {
            return None;
        }
        if !cw && step < -0.05 {
            return None;
        }
        prev = ang;
    }
    let total = sweep(a0, a1);
    if cw && total >= -0.15 {
        return None;
    }
    if !cw && total <= 0.15 {
        return None;
    }
    if (a1 - am).abs() < 1e-6 {
        return None;
    }
    let length = r * total.abs();
    let chord = hypot(c[0] - a[0], c[1] - a[1]);
    if length < chord + 1e-4 {
        return None;
    }
    let tangent = if cw {
        [a[1] - center[1], center[0] - a[0]]
    } else {
        [center[1] - a[1], a[0] - center[0]]
    };
    Some(ArcFit {
        end: c,
        ij: [center[0] - a[0], center[1] - a[1]],
        cw,
        length,
        dir: tangent,
    })
}

fn sweep(from: f64, to: f64) -> f64 {
    let mut d = to - from;
    while d > std::f64::consts::PI {
        d -= std::f64::consts::TAU;
    }
    while d < -std::f64::consts::PI {
        d += std::f64::consts::TAU;
    }
    d
}

fn circumcenter(a: [f64; 2], b: [f64; 2], c: [f64; 2]) -> Option<[f64; 2]> {
    let d = 2.0 * (a[0] * (b[1] - c[1]) + b[0] * (c[1] - a[1]) + c[0] * (a[1] - b[1]));
    if d.abs() < 1e-8 {
        return None;
    }
    let a2 = a[0] * a[0] + a[1] * a[1];
    let b2 = b[0] * b[0] + b[1] * b[1];
    let c2 = c[0] * c[0] + c[1] * c[1];
    Some([
        (a2 * (b[1] - c[1]) + b2 * (c[1] - a[1]) + c2 * (a[1] - b[1])) / d,
        (a2 * (c[0] - b[0]) + b2 * (a[0] - c[0]) + c2 * (b[0] - a[0])) / d,
    ])
}
