import { legacyStockEnd, legacyStockStart, spliceText, withMachineGcode } from "./machine-gcode.ts";

let failed = 0;

function eq(name: string, got: unknown, want: unknown): void {
  const a = JSON.stringify(got);
  const b = JSON.stringify(want);
  if (a === b) return;
  failed += 1;
  console.error(`FAIL ${name}\n  got  ${a}\n  want ${b}`);
}

const engine = [
  "; generated by Lime Slice — FDM strategy blender",
  "; printer: Lime 220",
  "; features: seam blend",
  "M140 S60",
  "M104 S200",
  "M190 S60",
  "M109 S200",
  "G21",
  "G90",
  "M82",
  "G28",
  "G92 E0",
  "M106 S0",
  ";LAYER:0 Z:0.200",
  "G1 X10 Y10 E0.1",
  "G1 Z10.200 F600",
  "M106 S0",
  "M104 S0",
  "M140 S0",
  "; bed 220x220 mm nozzle 0.40 mm",
  "; TIME:10.0s FILAMENT_MM:1.00 FILAMENT_G:0.003 ARCS:0",
  "M84",
  "",
].join("\n");

eq("blank text is the same bytes", withMachineGcode(engine, "", "  \n"), engine);
eq("a stock comment is blank", spliceText(legacyStockStart("Lime 220"), legacyStockStart("Lime 220")), "");
eq("a stock end comment is blank", spliceText(legacyStockEnd("Lime 220"), legacyStockEnd("Lime 220")), "");
eq("user text is kept", spliceText("G28 W ; home", legacyStockStart("Lime 220")), "G28 W ; home");

const wrapped = withMachineGcode(
  engine,
  spliceText("G4 P100 ; settle", legacyStockStart("Lime 220")),
  spliceText("M107 ; fan off", legacyStockEnd("Lime 220")),
);
// A vendor start purges and probes: it must run hot and after the engine's
// G28, and the engine must take back temperatures, modes and E after it.
eq(
  "start runs after heating and homing, and the engine restores its state",
  wrapped.includes(
    "M109 S200\nG21\nG90\nM82\nG28\nG92 E0\nG4 P100 ; settle\n" +
      "M140 S60\nM104 S200\nM190 S60\nM109 S200\nG90\nM82\nG92 E0\nM106 S0\n",
  ),
  true,
);
eq("the engine homes once before the start block", wrapped.indexOf("G28\n") < wrapped.indexOf("G4 P100"), true);
const purge = withMachineGcode(engine, "M83\nG1 X60 E9 F1000 ; purge", "");
eq(
  "E is zeroed and absolute after a relative purge",
  purge.includes("E9 F1000 ; purge\nM140 S60\nM104 S200\nM190 S60\nM109 S200\nG90\nM82\nG92 E0\n"),
  true,
);
eq(
  "a file that never homes takes the start after its comments",
  withMachineGcode("; head\nG1 X1\n", "G4 P1", ""),
  "; head\nG4 P1\nG90\nM82\nG92 E0\nG1 X1\n",
);
eq("end sits before the cooldown", wrapped.includes("M107 ; fan off\nM106 S0\nM104 S0\nM140 S0\n"), true);
eq("the engine homing line stays", wrapped.includes("G28\n"), true);
eq("a file with no cooldown appends the end", withMachineGcode("G1 X1\n", "", "M84 ; done"), "G1 X1\nM84 ; done\n");
eq("whitespace-only start does not move the file", withMachineGcode(engine, " \n\t", ""), engine);

if (failed > 0) {
  console.error(`${failed} failed`);
  throw new Error(`${failed} failed`);
}
console.log("machine-gcode: splice ok");
